### ISSUE TITLE
Now that it is running: how do I use this driver on Raspi with Python

### ISSUE THREAD

**Issue by ullix** [Sensirion/raspberry-pi-i2c-scd30#1]
My SCD30 is connected to Raspi, the code is compiled, the example_usage tells me the firmware of the sensor is 3.66, and the CO2, T, H values seem reasonable.

But have I missed it? How can I now use this driver on Raspi with Python???

**Comment by LeonieFierz** [comment]
Hello @ullix 
there is actually a Python driver for SCD30 you can use: https://github.com/Sensirion/python-i2c-scd30. Please check-out the Linux example (https://github.com/Sensirion/python-i2c-scd30/blob/master/examples/example_linux_scd30.py) and make sure to set the correct i2c port. You can use the same wiring as with the C Driver provided in this repository.
Hope this helps.

**Comment by ullix** [comment]
Thx, I'll try.
